/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "sanctum.csrf-cookie": [],
    "home": [],
    "optimize": [],
    "admin.dashboard.index": [],
    "admin.users.index": [],
    "admin.users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.edit": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.index": [],
    "admin.orders.create": [],
    "admin.orders.store": [],
    "admin.orders.show": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.confirm": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.assign-driver": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.edit": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.update": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.orders.destroy": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.toggle-status": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.index": [],
    "admin.products.create": [],
    "admin.products.store": [],
    "admin.products.show": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.edit": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.messages.index": [],
    "customer.dashboard": [],
    "customer.products.index": [],
    "customer.products.show": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "customer.cart.index": [],
    "customer.cart.add": [],
    "customer.cart.update": [
        {
            "name": "cart",
            "required": true,
            "binding": "id"
        }
    ],
    "customer.cart.destroy": [
        {
            "name": "cart",
            "required": true,
            "binding": "id"
        }
    ],
    "customer.orders.index": [],
    "customer.orders.create": [],
    "customer.orders.store": [],
    "customer.orders.show": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "customer.orders.cancel": [
        {
            "name": "order",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.orders.index": [],
    "api.v1.orders.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.orders.store": [],
    "api.products": [],
    "api.products.search": [],
    "api.customers.by-phone": [
        {
            "name": "phone",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
